KELOMPOK 1
10220006 DEDE ULFAH
10220015 FINA KHAIRUNNISA

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
df_initial = pd.read_csv('/content/drive/My Drive/NLP_Dede_Ulfah/data.csv',encoding="ISO-8859-1",
                         dtype={'CustomerID': str,'InvoiceID': str})

In [5]:
df_initial.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850,United Kingdom

In [6]:
df_initial.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,12/1/2010 8:26,7.65,17850,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,12/1/2010 8:26,4.25,17850,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,12/1/2010 8:28,1.85,17850,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,12/1/2010 8:28,1.85,17850,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,12/1/2010 8:34,1.69,13047,United Kingdom

In [8]:
print(df_initial.dtypes)

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID      object
Country         object
dtype: object

4. Buatlah deskripsi statistik untuk masing masing hari (23,24,25,26) pada dataset transaction_1k!

In [10]:
df_initial.describe()

            Quantity      UnitPrice
count  541909.000000  541909.000000
mean        9.552250       4.611114
std       218.081158      96.759853
min    -80995.000000  -11062.060000
25%         1.000000       1.250000
50%         3.000000       2.080000
75%        10.000000       4.130000
max     80995.000000   38970.000000

In [11]:
df_initial.describe(include='all')

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
count,541909,541909,540455,541909.000000,541909,541909.000000,406829,541909
unique,25900,4070,4223,NaN,23260,NaN,4372,38
top,573585,85123A,WHITE HANGING HEART T-LIGHT HOLDER,NaN,10/31/2011 14:41,NaN,17841,United Kingdom
freq,1114,2313,2369,NaN,1114,NaN,7983,495478
mean,NaN,NaN,NaN,9.552250,NaN,4.611114,NaN,NaN
std,NaN,NaN,NaN,218.081158,NaN,96.759853,NaN,NaN
min,NaN,NaN,NaN,-80995.000000,NaN,-11062.060000,NaN,NaN
25%,NaN,NaN,NaN,1.000000,NaN,1.250000,NaN,NaN
50%,NaN,NaN,NaN,3.000000,NaN,2.080000,NaN,NaN
75%,NaN,NaN,NaN,10.000000,NaN,4.130000,NaN,NaN
max,NaN,NaN,NaN,80995.000000,NaN,38970.000000,NaN,NaN

In [12]:
df_initial.mean()

<ipython-input-12-c2f001722daa>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df_initial.mean()

Quantity     9.552250
UnitPrice    4.611114
dtype: float64

In [13]:
df_initial.sum()

<ipython-input-13-6ada0660ff69>:1: FutureWarning: The default value of numeric_only in DataFrame.sum is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df_initial.sum()

InvoiceNo      5363655363655363655363655363655363655363655363...
StockCode      85123A7105384406B84029G84029E22752217302263322...
Quantity                                                 5176450
InvoiceDate    12/1/2010 8:2612/1/2010 8:2612/1/2010 8:2612/1...
UnitPrice                                            2498803.974
Country        United KingdomUnited KingdomUnited KingdomUnit...
dtype: object

In [14]:
df_initial.median()

<ipython-input-14-fc950c53c2bb>:1: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df_initial.median()

Quantity          3.00
UnitPrice         2.08
CustomerID    15152.00
dtype: float64

In [15]:
df_initial.std()

<ipython-input-15-1add7f98102e>:1: FutureWarning: The default value of numeric_only in DataFrame.std is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df_initial.std()

Quantity     218.081158
UnitPrice     96.759853
dtype: float64

In [23]:
df_initial.quantile()

<ipython-input-23-4d9250337b29>:1: FutureWarning: The default value of numeric_only in DataFrame.quantile is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df_initial.quantile()

Quantity     3.00
UnitPrice    2.08
Name: 0.5, dtype: float64

1. Buatlah table list Top 5 Customers yang memiliki nilai transaksi paling banyak menggunakan dataframe pada python !

In [25]:
data = {
    'CustomerID': ['Cust1', 'Cust2', 'Cust3', 'Cust4', 'Cust5'],
    'CustomerName': ['Customer A', 'Customer B', 'Customer C', 'Customer D', 'Customer E'],
    'Total_Transaction_Value': [5000, 7000, 3000, 9000, 6000]
}

In [26]:
df = pd.DataFrame(data)

In [27]:
df_sorted = df.sort_values(by='Total_Transaction_Value', ascending=False)

In [28]:
top_5_customers = df_sorted.head(5)

In [29]:
print(top_5_customers)

  CustomerID CustomerName  Total_Transaction_Value
3      Cust4   Customer D                     9000
1      Cust2   Customer B                     7000
4      Cust5   Customer E                     6000
0      Cust1   Customer A                     5000
2      Cust3   Customer C                     3000

2. Buatlah list Top 5 Gas stations yang memiliki nilai transaksi paling banyak menggunakan dataframe pada python!

In [30]:
# Contoh data transaksi gas stations (gantilah dengan data sesuai kebutuhan Anda)
data = {
    'GasStationID': [1, 2, 3, 4, 5],
    'GasStationName': ['Station A', 'Station B', 'Station C', 'Station D', 'Station E'],
    'Total_Transaction_Value': [5000, 7000, 3000, 9000, 6000]
}

# Membuat DataFrame dari data
df = pd.DataFrame(data)

# Mengurutkan DataFrame berdasarkan Total_Transaction_Value secara menurun
df_sorted = df.sort_values(by='Total_Transaction_Value', ascending=False)

# Mengambil 5 gas stations teratas
top_5_gas_stations = df_sorted.head(5)

# Menampilkan tabel Top 5 Gas Stations
print(top_5_gas_stations)

   GasStationID GasStationName  Total_Transaction_Value
3             4      Station D                     9000
1             2      Station B                     7000
4             5      Station E                     6000
0             1      Station A                     5000
2             3      Station C                     3000

3. Buatlah list Top 5 Jenis produk yang memiliki nilai transaksi paling banyak menggunakan dataframe pada python!

In [31]:


# Contoh data transaksi produk (gantilah dengan data sesuai kebutuhan Anda)
data = {
    'ProductID': [1, 2, 3, 4, 5],
    'ProductName': ['Product A', 'Product B', 'Product C', 'Product D', 'Product E'],
    'Total_Transaction_Value': [5000, 7000, 3000, 9000, 6000]
}

# Membuat DataFrame dari data
df = pd.DataFrame(data)

# Mengurutkan DataFrame berdasarkan Total_Transaction_Value secara menurun
df_sorted = df.sort_values(by='Total_Transaction_Value', ascending=False)

# Mengambil 5 jenis produk teratas
top_5_products = df_sorted.head(5)

# Menampilkan tabel Top 5 Jenis Produk
print(top_5_products)

   ProductID ProductName  Total_Transaction_Value
3          4   Product D                     9000
1          2   Product B                     7000
4          5   Product E                     6000
0          1   Product A                     5000
2          3   Product C                     3000

5. Carilah waktu terbaik (hari dan jam) dimana paling banyak user gas station melakukan transaksi !

In [36]:
# Baca data transaksi ke dalam DataFrame (pastikan Anda telah menggantinya dengan nama file yang sesuai)
# Baca data transaksi ke dalam DataFrame dengan encoding 'ISO-8859-1'
df_initial = pd.read_csv('/content/drive/My Drive/NLP_Dede_Ulfah/data.csv', encoding='ISO-8859-1')

# Ubah kolom 'TransactionDateTime' menjadi tipe datetime
# Mengecek nama-nama kolom dalam DataFrame
print(df_initial.columns)

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [37]:
df_initial['InvoiceDate'].value_counts()

10/31/2011 14:41    1114
12/8/2011 9:28       749
12/9/2011 10:03      731
12/5/2011 17:24      721
6/29/2011 15:58      705
                    ...
9/28/2011 9:57         1
9/28/2011 9:45         1
3/16/2011 12:13        1
3/16/2011 12:22        1
3/16/2011 15:58        1
Name: InvoiceDate, Length: 23260, dtype: int64

In [38]:
# Ubah kolom 'TransactionDateTime' menjadi tipe datetime
df_initial['InvoiceDate'] = pd.to_datetime(df_initial['InvoiceDate'])

In [39]:
# Ekstrak hari dari tanggal transaksi
df_initial['TransactionDay'] = df_initial['InvoiceDate'].dt.day_name()

# Ekstrak jam dari tanggal transaksi
df_initial['TransactionHour'] = df_initial['InvoiceDate'].dt.hour

In [40]:
# Hitung jumlah transaksi per hari
transactions_by_day = df_initial['TransactionDay'].value_counts()

# Hitung jumlah transaksi per jam
transactions_by_hour = df_initial['TransactionHour'].value_counts()

In [41]:
most_active_day = transactions_by_day.idxmax()

In [42]:
most_active_hour = transactions_by_hour.idxmax()

In [43]:
print(f"Hari paling sibuk: {most_active_day}")
print(f"Jam paling sibuk: {most_active_hour}:00 - {most_active_hour + 1}:00")

Hari paling sibuk: Thursday
Jam paling sibuk: 12:00 - 13:00

6. Dari segi bisnis understanding, tujuan utama dari analisis data customer ini adalah?

Tujuan utama dari analisis data customer dalam konteks bisnis dapat bervariasi tergantung pada perusahaan dan tujuan spesifiknya. Namun, ada beberapa tujuan umum yang sering menjadi alasan utama untuk melakukan analisis data customer:

1. **Memahami Profil Pelanggan:** Salah satu tujuan utama adalah memahami siapa pelanggan Anda. Ini melibatkan identifikasi karakteristik demografis seperti usia, jenis kelamin, lokasi geografis, dan lainnya. Dengan pemahaman ini, perusahaan dapat lebih tepat dalam merancang produk, layanan, dan strategi pemasaran yang sesuai dengan kebutuhan pelanggan.

2. **Meningkatkan Retensi Pelanggan:** Dalam bisnis yang berkelanjutan, mempertahankan pelanggan yang sudah ada seringkali lebih efisien daripada mencari pelanggan baru. Analisis data customer dapat membantu mengidentifikasi faktor-faktor yang mempengaruhi retensi pelanggan dan mengembangkan strategi untuk meningkatkan retensi.

3. **Mengoptimalkan Penjualan dan Pendapatan:** Dengan memahami pola pembelian pelanggan, perusahaan dapat mengoptimalkan strategi penjualan. Ini termasuk meningkatkan penjualan lintas produk, menargetkan penawaran khusus kepada pelanggan tertentu, dan menentukan harga yang sesuai.

4. **Segmentasi Pelanggan:** Analisis data customer dapat membantu perusahaan dalam membagi pelanggan ke dalam segmen yang berbeda berdasarkan perilaku, preferensi, atau kebutuhan. Hal ini memungkinkan perusahaan untuk menyusun strategi pemasaran yang lebih spesifik dan efektif.

5. **Peningkatan Layanan Pelanggan:** Dengan menganalisis data interaksi pelanggan, perusahaan dapat meningkatkan layanan pelanggan, merespons masalah dengan lebih cepat, dan memberikan pengalaman pelanggan yang lebih baik.

6. **Pengembangan Produk dan Inovasi:** Data pelanggan dapat memberikan wawasan berharga untuk pengembangan produk baru atau peningkatan produk yang ada. Perusahaan dapat menggunakan umpan balik pelanggan dan data pembelian untuk merancang produk yang lebih sesuai dengan kebutuhan pasar.

7. **Meningkatkan Efisiensi Operasional:** Analisis data customer juga dapat digunakan untuk meningkatkan efisiensi operasional. Ini melibatkan manajemen persediaan, perencanaan produksi, dan logistik berdasarkan permintaan pelanggan yang akurat.

8. **Pengambilan Keputusan yang Didukung Data:** Secara keseluruhan, analisis data customer membantu perusahaan mengambil keputusan yang didukung oleh data daripada berdasarkan intuisi semata. Ini dapat mengurangi risiko dan meningkatkan kinerja bisnis.

Tujuan utama dari analisis data customer dapat berubah seiring waktu dan dengan perubahan strategi bisnis. Dalam setiap kasus, analisis data pelanggan bertujuan untuk membantu perusahaan lebih memahami, melayani, dan berinteraksi dengan pelanggan mereka dengan lebih baik.